version: "3.0"
# See Contribution Guidelines in README. Redis 7.2.4 is the last redis version before the Valkey fork.
services:
  SingleNodeRedis:
    restart: always
    image: redis:${REDIS_VERSION:-7.2.4}
    ports:
      - "6379:6379"
    environment:
      - DEBUG=false
    command: redis-server --notify-keyspace-events KEA

  ReplicaNode:
    restart: always
    image: redis:${REDIS_VERSION:-7.2.4}
    ports:
      - "6380:6379"
    command: redis-server --replicaof SingleNodeRedis 6379
    links:
      - SingleNodeRedis:SingleNodeRedis
    environment:
      - DEBUG=false

  RedisCluster:
    restart: always
    image: grokzen/redis-cluster:${REDIS_VERSION:-7.2.4}
    ports:
      - "30001:30001"
      - "30002:30002"
      - "30003:30003"
      - "30004:30004"
      - "30005:30005"
      - "30006:30006"
    environment:
      - INITIAL_PORT=30001
      - DEBUG=false
      
