package dev.profunktor.valkey4cats.ffi

private[valkey4cats] opaque type CmdOrdinal = Int
private[valkey4cats] object CmdOrdinal:
  inline def apply(inline n: Int): CmdOrdinal = n
  extension (c: CmdOrdinal) inline def toInt: Int = c

/** Maps command type ordinals to the Rust `RequestType` enum in libglide_ffi.
  *
  * Values must match the Rust enum exactly so that the FFI layer dispatches to the correct handler.
  */
private[valkey4cats] object CommandType:
  private inline def cmd(inline n: Int): CmdOrdinal = CmdOrdinal(n)

  // ── General ──────────────────────────────────────────────────────────
  inline def InvalidRequest: CmdOrdinal = cmd(0)
  inline def CustomCommand: CmdOrdinal  = cmd(1)

  // ── Bitmap (1xx) ─────────────────────────────────────────────────────
  inline def BitCount: CmdOrdinal = cmd(101)
  inline def BitField: CmdOrdinal = cmd(102)
  inline def BitFieldReadOnly: CmdOrdinal = cmd(103)
  inline def BitOp: CmdOrdinal = cmd(104)
  inline def BitPos: CmdOrdinal = cmd(105)
  inline def GetBit: CmdOrdinal = cmd(106)
  inline def SetBit: CmdOrdinal = cmd(107)

  // ── Cluster (2xx) ────────────────────────────────────────────────────
  inline def Asking: CmdOrdinal = cmd(201)
  inline def ClusterAddSlots: CmdOrdinal = cmd(202)
  inline def ClusterAddSlotsRange: CmdOrdinal = cmd(203)
  inline def ClusterBumpEpoch: CmdOrdinal = cmd(204)
  inline def ClusterCountFailureReports: CmdOrdinal = cmd(205)
  inline def ClusterCountKeysInSlot: CmdOrdinal = cmd(206)
  inline def ClusterDelSlots: CmdOrdinal = cmd(207)
  inline def ClusterDelSlotsRange: CmdOrdinal = cmd(208)
  inline def ClusterFailover: CmdOrdinal = cmd(209)
  inline def ClusterFlushSlots: CmdOrdinal = cmd(210)
  inline def ClusterForget: CmdOrdinal = cmd(211)
  inline def ClusterGetKeysInSlot: CmdOrdinal = cmd(212)
  inline def ClusterInfo: CmdOrdinal = cmd(213)
  inline def ClusterKeySlot: CmdOrdinal = cmd(214)
  inline def ClusterLinks: CmdOrdinal = cmd(215)
  inline def ClusterMeet: CmdOrdinal = cmd(216)
  inline def ClusterMyId: CmdOrdinal = cmd(217)
  inline def ClusterMyShardId: CmdOrdinal = cmd(218)
  inline def ClusterNodes: CmdOrdinal = cmd(219)
  inline def ClusterReplicas: CmdOrdinal = cmd(220)
  inline def ClusterReplicate: CmdOrdinal = cmd(221)
  inline def ClusterReset: CmdOrdinal = cmd(222)
  inline def ClusterSaveConfig: CmdOrdinal = cmd(223)
  inline def ClusterSetConfigEpoch: CmdOrdinal = cmd(224)
  inline def ClusterSetslot: CmdOrdinal = cmd(225)
  inline def ClusterShards: CmdOrdinal = cmd(226)
  inline def ClusterSlaves: CmdOrdinal = cmd(227)
  inline def ClusterSlots: CmdOrdinal = cmd(228)
  inline def ReadOnly: CmdOrdinal = cmd(229)
  inline def ReadWrite: CmdOrdinal = cmd(230)

  // ── Connection (3xx) ─────────────────────────────────────────────────
  inline def Auth: CmdOrdinal = cmd(301)
  inline def ClientCaching: CmdOrdinal = cmd(302)
  inline def ClientGetName: CmdOrdinal = cmd(303)
  inline def ClientGetRedir: CmdOrdinal = cmd(304)
  inline def ClientId: CmdOrdinal = cmd(305)
  inline def ClientInfo: CmdOrdinal = cmd(306)
  inline def ClientKillSimple: CmdOrdinal = cmd(307)
  inline def ClientKill: CmdOrdinal = cmd(308)
  inline def ClientList: CmdOrdinal = cmd(309)
  inline def ClientNoEvict: CmdOrdinal = cmd(310)
  inline def ClientNoTouch: CmdOrdinal = cmd(311)
  inline def ClientPause: CmdOrdinal = cmd(312)
  inline def ClientReply: CmdOrdinal = cmd(313)
  inline def ClientSetInfo: CmdOrdinal = cmd(314)
  inline def ClientSetName: CmdOrdinal = cmd(315)
  inline def ClientTracking: CmdOrdinal = cmd(316)
  inline def ClientTrackingInfo: CmdOrdinal = cmd(317)
  inline def ClientUnblock: CmdOrdinal = cmd(318)
  inline def ClientUnpause: CmdOrdinal = cmd(319)
  inline def Echo: CmdOrdinal = cmd(320)
  inline def Hello: CmdOrdinal = cmd(321)
  inline def Ping: CmdOrdinal = cmd(322)
  inline def Quit: CmdOrdinal = cmd(323)
  inline def Reset: CmdOrdinal = cmd(324)
  inline def Select: CmdOrdinal = cmd(325)

  // ── Generic / Key (4xx) ──────────────────────────────────────────────
  inline def Copy: CmdOrdinal = cmd(401)
  inline def Del: CmdOrdinal = cmd(402)
  inline def Dump: CmdOrdinal = cmd(403)
  inline def Exists: CmdOrdinal = cmd(404)
  inline def Expire: CmdOrdinal = cmd(405)
  inline def ExpireAt: CmdOrdinal = cmd(406)
  inline def ExpireTime: CmdOrdinal = cmd(407)
  inline def Keys: CmdOrdinal = cmd(408)
  inline def Migrate: CmdOrdinal = cmd(409)
  inline def Move: CmdOrdinal = cmd(410)
  inline def ObjectEncoding: CmdOrdinal = cmd(411)
  inline def ObjectFreq: CmdOrdinal = cmd(412)
  inline def ObjectIdleTime: CmdOrdinal = cmd(413)
  inline def ObjectRefCount: CmdOrdinal = cmd(414)
  inline def Persist: CmdOrdinal = cmd(415)
  inline def PExpire: CmdOrdinal = cmd(416)
  inline def PExpireAt: CmdOrdinal = cmd(417)
  inline def PExpireTime: CmdOrdinal = cmd(418)
  inline def PTTL: CmdOrdinal = cmd(419)
  inline def RandomKey: CmdOrdinal = cmd(420)
  inline def Rename: CmdOrdinal = cmd(421)
  inline def RenameNX: CmdOrdinal = cmd(422)
  inline def Restore: CmdOrdinal = cmd(423)
  inline def Scan: CmdOrdinal = cmd(424)
  inline def Sort: CmdOrdinal = cmd(425)
  inline def SortReadOnly: CmdOrdinal = cmd(426)
  inline def Touch: CmdOrdinal = cmd(427)
  inline def TTL: CmdOrdinal = cmd(428)
  inline def Type: CmdOrdinal = cmd(429)
  inline def Unlink: CmdOrdinal = cmd(430)
  inline def Wait: CmdOrdinal = cmd(431)
  inline def WaitAof: CmdOrdinal = cmd(432)

  // ── Geo (5xx) ────────────────────────────────────────────────────────
  inline def GeoAdd: CmdOrdinal = cmd(501)
  inline def GeoDist: CmdOrdinal = cmd(502)
  inline def GeoHash: CmdOrdinal = cmd(503)
  inline def GeoPos: CmdOrdinal = cmd(504)
  inline def GeoRadius: CmdOrdinal = cmd(505)
  inline def GeoRadiusReadOnly: CmdOrdinal = cmd(506)
  inline def GeoRadiusByMember: CmdOrdinal = cmd(507)
  inline def GeoRadiusByMemberReadOnly: CmdOrdinal = cmd(508)
  inline def GeoSearch: CmdOrdinal = cmd(509)
  inline def GeoSearchStore: CmdOrdinal = cmd(510)

  // ── Hash (6xx) ───────────────────────────────────────────────────────
  inline def HDel: CmdOrdinal = cmd(601)
  inline def HExists: CmdOrdinal = cmd(602)
  inline def HGet: CmdOrdinal = cmd(603)
  inline def HGetAll: CmdOrdinal = cmd(604)
  inline def HIncrBy: CmdOrdinal = cmd(605)
  inline def HIncrByFloat: CmdOrdinal = cmd(606)
  inline def HKeys: CmdOrdinal = cmd(607)
  inline def HLen: CmdOrdinal = cmd(608)
  inline def HMGet: CmdOrdinal = cmd(609)
  inline def HMSet: CmdOrdinal = cmd(610)
  inline def HRandField: CmdOrdinal = cmd(611)
  inline def HScan: CmdOrdinal = cmd(612)
  inline def HSet: CmdOrdinal = cmd(613)
  inline def HSetNX: CmdOrdinal = cmd(614)
  inline def HStrlen: CmdOrdinal = cmd(615)
  inline def HVals: CmdOrdinal = cmd(616)

  // ── HyperLogLog (7xx) ────────────────────────────────────────────────
  inline def PfAdd: CmdOrdinal = cmd(701)
  inline def PfCount: CmdOrdinal = cmd(702)
  inline def PfMerge: CmdOrdinal = cmd(703)

  // ── List (8xx) ───────────────────────────────────────────────────────
  inline def BLMove: CmdOrdinal = cmd(801)
  inline def BLMPop: CmdOrdinal = cmd(802)
  inline def BLPop: CmdOrdinal = cmd(803)
  inline def BRPop: CmdOrdinal = cmd(804)
  inline def BRPopLPush: CmdOrdinal = cmd(805)
  inline def LIndex: CmdOrdinal = cmd(806)
  inline def LInsert: CmdOrdinal = cmd(807)
  inline def LLen: CmdOrdinal = cmd(808)
  inline def LMove: CmdOrdinal = cmd(809)
  inline def LMPop: CmdOrdinal = cmd(810)
  inline def LPop: CmdOrdinal = cmd(811)
  inline def LPos: CmdOrdinal = cmd(812)
  inline def LPush: CmdOrdinal = cmd(813)
  inline def LPushX: CmdOrdinal = cmd(814)
  inline def LRange: CmdOrdinal = cmd(815)
  inline def LRem: CmdOrdinal = cmd(816)
  inline def LSet: CmdOrdinal = cmd(817)
  inline def LTrim: CmdOrdinal = cmd(818)
  inline def RPop: CmdOrdinal = cmd(819)
  inline def RPopLPush: CmdOrdinal = cmd(820)
  inline def RPush: CmdOrdinal = cmd(821)
  inline def RPushX: CmdOrdinal = cmd(822)

  // ── PubSub (9xx) ────────────────────────────────────────────────────
  inline def PSubscribe: CmdOrdinal = cmd(901)
  inline def Publish: CmdOrdinal = cmd(902)
  inline def PubSubChannels: CmdOrdinal = cmd(903)
  inline def PubSubNumPat: CmdOrdinal = cmd(904)
  inline def PubSubNumSub: CmdOrdinal = cmd(905)
  inline def PubSubShardChannels: CmdOrdinal = cmd(906)
  inline def PubSubShardNumSub: CmdOrdinal = cmd(907)
  inline def PUnsubscribe: CmdOrdinal = cmd(908)
  inline def SPublish: CmdOrdinal = cmd(909)
  inline def SSubscribe: CmdOrdinal = cmd(910)
  inline def Subscribe: CmdOrdinal = cmd(911)
  inline def SUnsubscribe: CmdOrdinal = cmd(912)
  inline def Unsubscribe: CmdOrdinal = cmd(913)

  // ── Scripting (10xx) ─────────────────────────────────────────────────
  inline def Eval: CmdOrdinal = cmd(1001)
  inline def EvalReadOnly: CmdOrdinal = cmd(1002)
  inline def EvalSha: CmdOrdinal = cmd(1003)
  inline def EvalShaReadOnly: CmdOrdinal = cmd(1004)
  inline def FCall: CmdOrdinal = cmd(1005)
  inline def FCallReadOnly: CmdOrdinal = cmd(1006)
  inline def FunctionDelete: CmdOrdinal = cmd(1007)
  inline def FunctionDump: CmdOrdinal = cmd(1008)
  inline def FunctionFlush: CmdOrdinal = cmd(1009)
  inline def FunctionKill: CmdOrdinal = cmd(1010)
  inline def FunctionList: CmdOrdinal = cmd(1011)
  inline def FunctionLoad: CmdOrdinal = cmd(1012)
  inline def FunctionRestore: CmdOrdinal = cmd(1013)
  inline def FunctionStats: CmdOrdinal = cmd(1014)
  inline def ScriptDebug: CmdOrdinal = cmd(1015)
  inline def ScriptExists: CmdOrdinal = cmd(1016)
  inline def ScriptFlush: CmdOrdinal = cmd(1017)
  inline def ScriptKill: CmdOrdinal = cmd(1018)
  inline def ScriptLoad: CmdOrdinal = cmd(1019)
  inline def ScriptShow: CmdOrdinal = cmd(1020)

  // ── Server (11xx) ────────────────────────────────────────────────────
  inline def AclCat: CmdOrdinal = cmd(1101)
  inline def AclDelUser: CmdOrdinal = cmd(1102)
  inline def AclDryRun: CmdOrdinal = cmd(1103)
  inline def AclGenPass: CmdOrdinal = cmd(1104)
  inline def AclGetUser: CmdOrdinal = cmd(1105)
  inline def AclList: CmdOrdinal = cmd(1106)
  inline def AclLoad: CmdOrdinal = cmd(1107)
  inline def AclLog: CmdOrdinal = cmd(1108)
  inline def AclSave: CmdOrdinal = cmd(1109)
  inline def AclSetSser: CmdOrdinal = cmd(1110)
  inline def AclUsers: CmdOrdinal = cmd(1111)
  inline def AclWhoami: CmdOrdinal = cmd(1112)
  inline def BgRewriteAof: CmdOrdinal = cmd(1113)
  inline def BgSave: CmdOrdinal = cmd(1114)
  inline def Command_ : CmdOrdinal = cmd(1115)
  inline def CommandCount: CmdOrdinal = cmd(1116)
  inline def CommandDocs: CmdOrdinal = cmd(1117)
  inline def CommandGetKeys: CmdOrdinal = cmd(1118)
  inline def CommandGetKeysAndFlags: CmdOrdinal = cmd(1119)
  inline def CommandInfo: CmdOrdinal = cmd(1120)
  inline def CommandList: CmdOrdinal = cmd(1121)
  inline def ConfigGet: CmdOrdinal = cmd(1122)
  inline def ConfigResetStat: CmdOrdinal = cmd(1123)
  inline def ConfigRewrite: CmdOrdinal = cmd(1124)
  inline def ConfigSet: CmdOrdinal = cmd(1125)
  inline def DBSize: CmdOrdinal = cmd(1126)
  inline def FailOver: CmdOrdinal = cmd(1127)
  inline def FlushAll: CmdOrdinal = cmd(1128)
  inline def FlushDB: CmdOrdinal = cmd(1129)
  inline def Info: CmdOrdinal = cmd(1130)
  inline def LastSave: CmdOrdinal = cmd(1131)
  inline def LatencyDoctor: CmdOrdinal = cmd(1132)
  inline def LatencyGraph: CmdOrdinal = cmd(1133)
  inline def LatencyHistogram: CmdOrdinal = cmd(1134)
  inline def LatencyHistory: CmdOrdinal = cmd(1135)
  inline def LatencyLatest: CmdOrdinal = cmd(1136)
  inline def LatencyReset: CmdOrdinal = cmd(1137)
  inline def Lolwut: CmdOrdinal = cmd(1138)
  inline def MemoryDoctor: CmdOrdinal = cmd(1139)
  inline def MemoryMallocStats: CmdOrdinal = cmd(1140)
  inline def MemoryPurge: CmdOrdinal = cmd(1141)
  inline def MemoryStats: CmdOrdinal = cmd(1142)
  inline def MemoryUsage: CmdOrdinal = cmd(1143)
  inline def ModuleList: CmdOrdinal = cmd(1144)
  inline def ModuleLoad: CmdOrdinal = cmd(1145)
  inline def ModuleLoadEx: CmdOrdinal = cmd(1146)
  inline def ModuleUnload: CmdOrdinal = cmd(1147)
  inline def Monitor: CmdOrdinal = cmd(1148)
  inline def PSync: CmdOrdinal = cmd(1149)
  inline def ReplConf: CmdOrdinal = cmd(1150)
  inline def ReplicaOf: CmdOrdinal = cmd(1151)
  inline def RestoreAsking: CmdOrdinal = cmd(1152)
  inline def Role: CmdOrdinal = cmd(1153)
  inline def Save: CmdOrdinal = cmd(1154)
  inline def ShutDown: CmdOrdinal = cmd(1155)
  inline def SlaveOf: CmdOrdinal = cmd(1156)
  inline def SlowLogGet: CmdOrdinal = cmd(1157)
  inline def SlowLogLen: CmdOrdinal = cmd(1158)
  inline def SlowLogReset: CmdOrdinal = cmd(1159)
  inline def SwapDb: CmdOrdinal = cmd(1160)
  inline def Sync: CmdOrdinal = cmd(1161)
  inline def Time: CmdOrdinal = cmd(1162)

  // ── Set (12xx) ───────────────────────────────────────────────────────
  inline def SAdd: CmdOrdinal = cmd(1201)
  inline def SCard: CmdOrdinal = cmd(1202)
  inline def SDiff: CmdOrdinal = cmd(1203)
  inline def SDiffStore: CmdOrdinal = cmd(1204)
  inline def SInter: CmdOrdinal = cmd(1205)
  inline def SInterCard: CmdOrdinal = cmd(1206)
  inline def SInterStore: CmdOrdinal = cmd(1207)
  inline def SIsMember: CmdOrdinal = cmd(1208)
  inline def SMembers: CmdOrdinal = cmd(1209)
  inline def SMIsMember: CmdOrdinal = cmd(1210)
  inline def SMove: CmdOrdinal = cmd(1211)
  inline def SPop: CmdOrdinal = cmd(1212)
  inline def SRandMember: CmdOrdinal = cmd(1213)
  inline def SRem: CmdOrdinal = cmd(1214)
  inline def SScan: CmdOrdinal = cmd(1215)
  inline def SUnion: CmdOrdinal = cmd(1216)
  inline def SUnionStore: CmdOrdinal = cmd(1217)

  // ── Sorted Set (13xx) ────────────────────────────────────────────────
  inline def BZMPop: CmdOrdinal = cmd(1301)
  inline def BZPopMax: CmdOrdinal = cmd(1302)
  inline def BZPopMin: CmdOrdinal = cmd(1303)
  inline def ZAdd: CmdOrdinal = cmd(1304)
  inline def ZCard: CmdOrdinal = cmd(1305)
  inline def ZCount: CmdOrdinal = cmd(1306)
  inline def ZDiff: CmdOrdinal = cmd(1307)
  inline def ZDiffStore: CmdOrdinal = cmd(1308)
  inline def ZIncrBy: CmdOrdinal = cmd(1309)
  inline def ZInter: CmdOrdinal = cmd(1310)
  inline def ZInterCard: CmdOrdinal = cmd(1311)
  inline def ZInterStore: CmdOrdinal = cmd(1312)
  inline def ZLexCount: CmdOrdinal = cmd(1313)
  inline def ZMPop: CmdOrdinal = cmd(1314)
  inline def ZMScore: CmdOrdinal = cmd(1315)
  inline def ZPopMax: CmdOrdinal = cmd(1316)
  inline def ZPopMin: CmdOrdinal = cmd(1317)
  inline def ZRandMember: CmdOrdinal = cmd(1318)
  inline def ZRange: CmdOrdinal = cmd(1319)
  inline def ZRangeByLex: CmdOrdinal = cmd(1320)
  inline def ZRangeByScore: CmdOrdinal = cmd(1321)
  inline def ZRangeStore: CmdOrdinal = cmd(1322)
  inline def ZRank: CmdOrdinal = cmd(1323)
  inline def ZRem: CmdOrdinal = cmd(1324)
  inline def ZRemRangeByLex: CmdOrdinal = cmd(1325)
  inline def ZRemRangeByRank: CmdOrdinal = cmd(1326)
  inline def ZRemRangeByScore: CmdOrdinal = cmd(1327)
  inline def ZRevRange: CmdOrdinal = cmd(1328)
  inline def ZRevRangeByLex: CmdOrdinal = cmd(1329)
  inline def ZRevRangeByScore: CmdOrdinal = cmd(1330)
  inline def ZRevRank: CmdOrdinal = cmd(1331)
  inline def ZScan: CmdOrdinal = cmd(1332)
  inline def ZScore: CmdOrdinal = cmd(1333)
  inline def ZUnion: CmdOrdinal = cmd(1334)
  inline def ZUnionStore: CmdOrdinal = cmd(1335)

  // ── Stream (14xx) ────────────────────────────────────────────────────
  inline def XAck: CmdOrdinal = cmd(1401)
  inline def XAdd: CmdOrdinal = cmd(1402)
  inline def XAutoClaim: CmdOrdinal = cmd(1403)
  inline def XClaim: CmdOrdinal = cmd(1404)
  inline def XDel: CmdOrdinal = cmd(1405)
  inline def XGroupCreate: CmdOrdinal = cmd(1406)
  inline def XGroupCreateConsumer: CmdOrdinal = cmd(1407)
  inline def XGroupDelConsumer: CmdOrdinal = cmd(1408)
  inline def XGroupDestroy: CmdOrdinal = cmd(1409)
  inline def XGroupSetId: CmdOrdinal = cmd(1410)
  inline def XInfoConsumers: CmdOrdinal = cmd(1411)
  inline def XInfoGroups: CmdOrdinal = cmd(1412)
  inline def XInfoStream: CmdOrdinal = cmd(1413)
  inline def XLen: CmdOrdinal = cmd(1414)
  inline def XPending: CmdOrdinal = cmd(1415)
  inline def XRange: CmdOrdinal = cmd(1416)
  inline def XRead: CmdOrdinal = cmd(1417)
  inline def XReadGroup: CmdOrdinal = cmd(1418)
  inline def XRevRange: CmdOrdinal = cmd(1419)
  inline def XSetId: CmdOrdinal = cmd(1420)
  inline def XTrim: CmdOrdinal = cmd(1421)

  // ── String (15xx) ────────────────────────────────────────────────────
  inline def Append: CmdOrdinal = cmd(1501)
  inline def Decr: CmdOrdinal = cmd(1502)
  inline def DecrBy: CmdOrdinal = cmd(1503)
  inline def Get: CmdOrdinal = cmd(1504)
  inline def GetDel: CmdOrdinal = cmd(1505)
  inline def GetEx: CmdOrdinal = cmd(1506)
  inline def GetRange: CmdOrdinal = cmd(1507)
  inline def GetSet: CmdOrdinal = cmd(1508)
  inline def Incr: CmdOrdinal = cmd(1509)
  inline def IncrBy: CmdOrdinal = cmd(1510)
  inline def IncrByFloat: CmdOrdinal = cmd(1511)
  inline def LCS: CmdOrdinal = cmd(1512)
  inline def MGet: CmdOrdinal = cmd(1513)
  inline def MSet: CmdOrdinal = cmd(1514)
  inline def MSetNX: CmdOrdinal = cmd(1515)
  inline def PSetEx: CmdOrdinal = cmd(1516)
  inline def Set: CmdOrdinal = cmd(1517)
  inline def SetEx: CmdOrdinal = cmd(1518)
  inline def SetNX: CmdOrdinal = cmd(1519)
  inline def SetRange: CmdOrdinal = cmd(1520)
  inline def Strlen: CmdOrdinal = cmd(1521)
  inline def Substr: CmdOrdinal = cmd(1522)

  // ── Transaction (16xx) ───────────────────────────────────────────────
  inline def Discard: CmdOrdinal = cmd(1601)
  inline def Exec: CmdOrdinal = cmd(1602)
  inline def Multi: CmdOrdinal = cmd(1603)
  inline def UnWatch: CmdOrdinal = cmd(1604)
  inline def Watch: CmdOrdinal = cmd(1605)

  // ── JSON (20xx) ──────────────────────────────────────────────────────
  inline def JsonArrAppend: CmdOrdinal = cmd(2001)
  inline def JsonArrIndex: CmdOrdinal = cmd(2002)
  inline def JsonArrInsert: CmdOrdinal = cmd(2003)
  inline def JsonArrLen: CmdOrdinal = cmd(2004)
  inline def JsonArrPop: CmdOrdinal = cmd(2005)
  inline def JsonArrTrim: CmdOrdinal = cmd(2006)
  inline def JsonClear: CmdOrdinal = cmd(2007)
  inline def JsonDebug: CmdOrdinal = cmd(2008)
  inline def JsonDel: CmdOrdinal = cmd(2009)
  inline def JsonForget: CmdOrdinal = cmd(2010)
  inline def JsonGet: CmdOrdinal = cmd(2011)
  inline def JsonMGet: CmdOrdinal = cmd(2012)
  inline def JsonNumIncrBy: CmdOrdinal = cmd(2013)
  inline def JsonNumMultBy: CmdOrdinal = cmd(2014)
  inline def JsonObjKeys: CmdOrdinal = cmd(2015)
  inline def JsonObjLen: CmdOrdinal = cmd(2016)
  inline def JsonResp: CmdOrdinal = cmd(2017)
  inline def JsonSet: CmdOrdinal = cmd(2018)
  inline def JsonStrAppend: CmdOrdinal = cmd(2019)
  inline def JsonStrLen: CmdOrdinal = cmd(2020)
  inline def JsonToggle: CmdOrdinal = cmd(2021)
  inline def JsonType: CmdOrdinal = cmd(2022)

  // ── Search (21xx) ────────────────────────────────────────────────────
  inline def FtList: CmdOrdinal = cmd(2101)
  inline def FtAggregate: CmdOrdinal = cmd(2102)
  inline def FtAliasAdd: CmdOrdinal = cmd(2103)
  inline def FtAliasDel: CmdOrdinal = cmd(2104)
  inline def FtAliasList: CmdOrdinal = cmd(2105)
  inline def FtAliasUpdate: CmdOrdinal = cmd(2106)
  inline def FtCreate: CmdOrdinal = cmd(2107)
  inline def FtDropIndex: CmdOrdinal = cmd(2108)
  inline def FtExplain: CmdOrdinal = cmd(2109)
  inline def FtExplainCli: CmdOrdinal = cmd(2110)
  inline def FtInfo: CmdOrdinal = cmd(2111)
  inline def FtProfile: CmdOrdinal = cmd(2112)
  inline def FtSearch: CmdOrdinal = cmd(2113)

  // ── Aliases for NativeValkey naming conventions ──────────────────────
  inline def DbSize: CmdOrdinal         = DBSize
  inline def FlushDb: CmdOrdinal        = FlushDB
  inline def HSetNx: CmdOrdinal         = HSetNX
  inline def MSetNx: CmdOrdinal         = MSetNX
  inline def SetNx: CmdOrdinal          = SetNX
  inline def RenameNx: CmdOrdinal       = RenameNX
  inline def ObjectIdletime: CmdOrdinal = ObjectIdleTime
  inline def ObjectRefcount: CmdOrdinal = ObjectRefCount
  inline def Lcs: CmdOrdinal            = LCS
  inline def LcsLen: CmdOrdinal         = LCS
  inline def HStrLen: CmdOrdinal        = HStrlen

  // ── Commands not yet in Rust (dispatched via CustomCommand) ──────────
  inline def HExpire: CmdOrdinal          = CustomCommand
  inline def HExpireAt: CmdOrdinal        = CustomCommand
  inline def HExpireTime: CmdOrdinal      = CustomCommand
  inline def HPExpire: CmdOrdinal         = CustomCommand
  inline def HPExpireAt: CmdOrdinal       = CustomCommand
  inline def HPExpireTime: CmdOrdinal     = CustomCommand
  inline def HPTtl: CmdOrdinal            = CustomCommand
  inline def HPersist: CmdOrdinal         = CustomCommand
  inline def HTtl: CmdOrdinal             = CustomCommand
  inline def HGetEx: CmdOrdinal           = CustomCommand
  inline def HSetEx: CmdOrdinal           = CustomCommand
  inline def SortStore: CmdOrdinal        = CustomCommand
  inline def ZRangeWithScores: CmdOrdinal = CustomCommand
