name: Microsite

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "site/**"
      - "**/README.md"
      - "build.sbt"
      - "project/**"

jobs:
  publish:
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Install Nix"
        uses: cachix/install-nix-action@v31.2.0

      - name: "Install Cachix"
        uses: cachix/cachix-action@v16
        with:
          name: profunktor
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Build and publish microsite"
        run: nix run .#sbt -- publishSite
