name: Microsite

on:
  # to allow the manual trigger workflows
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "site/**"
      - "**/README.md"

jobs:
  publish:
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0 # fetch all branches & tags

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v31.2.0

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v16
        with:
          name: profunktor
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Building and publishing microsite 🚧"
        run: nix run .#sbt -- publishSite
